# Site settings
title: Hello World
header-img: img/home-bg.png
email: kerrydougherty@gmail.com
copyright_name: KerryAlsace
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Online Web Developer Program Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KerryAlsace
learn_profile: KerryAlsace
email_username: kerrydougherty@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
